version: 0.2

phases:

  install:
    commands:
      - pip install ansible
      - wget -q https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip
      - unzip packer_1.2.5_linux_amd64.zip

  pre_build:
    commands:
      - ansible-playbook --syntax-check ak.yml
      - ansible-playbook --syntax-check localhost.yml
      - aws cloudformation validate-template --template-body file://cf.yaml
      - ./packer validate packer.json

  build:
    commands:
      - echo ./packer build packer.json

  post_build:
    commands:
      - ./add_ami_to_template_parameters.py

artifacts:
  files:
    - cf.yml
    - cf-parameters.json
  name: cf
