version: 0.2

phases:

  install:
    commands:
      - wget -q https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip
      - unzip packer_1.2.5_linux_amd64.zip

  build:
    commands:
      - ./packer build packer.json

  post_build:
    commands:
      - python add_ami_to_template_parameters.py

artifacts:
  files:
    - cf.yaml
    - cf-parameters.json
  name: cf
