version: 0.2

phases:

  install:
    commands:
      - pip install ansible
      - wget https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip
      - unzip packer_1.2.5_linux_amd64.zip

  pre_build:
    commands:
      - ansible-playbook --syntax-check ak.yml
      - ansible-playbook --syntax-check localhost.yml
      - aws cloudformation validate-template --template-body file://cf.yaml
      - ./packer validate packer.json

  build:
    commands:
      - ./packer build packer.json

artifacts:
  files:
    - cf.yml
  name: cf
