---
Description: CF stack for building playbooks

Parameters:
  GitHubToken:
    Type: String
    Description: GitHub repository OAuth token - USE PARAMETER STORE
    NoEcho: True

Resources:

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  CodePipelineRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        -
          PolicyName: "CodePipelineNestedCFNAccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "codebuild:StartBuild"
                  - "codebuild:BatchGetBuilds"
                Resource:
                  - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${CBValidate}"
                  - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:build/${CBValidate}:*"
                  - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${CBPress}"
                  - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:build/${CBPress}:*"
                  - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${CBTest}"
                  - !Sub "arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:build/${CBTest}:*"
              -
                Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource:
                  - Fn::Sub: arn:aws:s3:::${ArtifactBucket}/*
                  - Fn::Sub: arn:aws:s3:::${ArtifactBucket}
              -
                Effect: "Allow"
                Action:
                  - "cloudformation:CreateChangeSet"
                  - "cloudformation:CreateStack"
                  - "cloudformation:CreateUploadBucket"
                  - "cloudformation:DeleteStack"
                  - "cloudformation:DeleteChangeSet"
                  - "cloudformation:Describe*"
                  - "cloudformation:List*"
                  - "cloudformation:UpdateStack"
                  - "cloudformation:ValidateTemplate"
                  - "cloudformation:ExecuteChangeSet"
                Resource:
                  - Fn::Sub: arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/Test-${AWS::StackName}*
                  - Fn::Sub: arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/UAT-${AWS::StackName}*
                  - Fn::Sub: arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/Prod-${AWS::StackName}*
              -
                Effect: "Allow"
                Action:
                  - "iam:PassRole"
                Resource:
                  - !GetAtt CloudFormationRole.Arn

  CodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /service-role/
      Policies:
        -
          PolicyName: "CodeBuild"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "cloudformation:Validate*"
                Resource:
                  - "*"
              -
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource:
                  - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
              -
                Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource:
                  - Fn::Sub: arn:aws:s3:::${ArtifactBucket}/*
                  - Fn::Sub: arn:aws:s3:::${ArtifactBucket}
              -
                Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:ListBucket"
                Resource:
                  - Fn::Sub: arn:aws:s3:::${ArtifactBucket}/*
                  - Fn::Sub: arn:aws:s3:::${ArtifactBucket}
              -
                Effect: "Allow"
                Action:
                  - "ec2:AttachVolume"
                  - "ec2:AuthorizeSecurityGroupIngress"
                  - "ec2:CopyImage"
                  - "ec2:CreateImage"
                  - "ec2:CreateKeypair"
                  - "ec2:CreateSecurityGroup"
                  - "ec2:CreateSnapshot"
                  - "ec2:CreateTags"
                  - "ec2:CreateVolume"
                  - "ec2:DeleteKeyPair"
                  - "ec2:DeleteSecurityGroup"
                  - "ec2:DeleteSnapshot"
                  - "ec2:DeleteVolume"
                  - "ec2:DeregisterImage"
                  - "ec2:DescribeImageAttribute"
                  - "ec2:DescribeImages"
                  - "ec2:DescribeInstances"
                  - "ec2:DescribeRegions"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeSnapshots"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeTags"
                  - "ec2:DescribeVolumes"
                  - "ec2:DetachVolume"
                  - "ec2:ModifyImageAttribute"
                  - "ec2:ModifyInstanceAttribute"
                  - "ec2:ModifySnapshotAttribute"
                  - "ec2:RegisterImage"
                  - "ec2:RunInstances"
                  - "ec2:StopInstances"
                  - "ec2:TerminateInstances"
                Resource:
                  - "*"

  CloudFormationRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "cloudformation.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        -
          PolicyName: "CloudFormationNestedCFNAccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "s3:*"
                Resource:
                  - "*"


  CBValidate:
    Type: AWS::CodeBuild::Project
    Properties:
      Description: Validate source
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-validate.yml
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/python:3.6.5
      Artifacts:
        Type: CODEPIPELINE
      TimeoutInMinutes: 5

  CBPress:
    Type: AWS::CodeBuild::Project
    Properties:
      Description: Validate and deploy playbooks
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-press.yml
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/python:3.6.5
      Artifacts:
        Type: CODEPIPELINE
      TimeoutInMinutes: 30

  CBTest:
    Type: AWS::CodeBuild::Project
    Properties:
      Description: Validate and deploy playbooks
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-test.yml
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/python:3.6.5
      Artifacts:
        Type: CODEPIPELINE
      TimeoutInMinutes: 5


  DeployPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        -
          Name: Checkout
          Actions:
            -
              Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: akinnane
                Repo: playbooks
                Branch: master
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                -
                  Name: github
        -
          Name: Validate
          Actions:
            -
              Name: CBValidate
              InputArtifacts:
                - Name: github
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CBValidate
              RunOrder: 1
        -
          Name: PressAmi
          Actions:
            -
              Name: PressAmi
              InputArtifacts:
                - Name: github
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                -
                  Name: CFTemplates
              Configuration:
                ProjectName: !Ref CBPress
              RunOrder: 2
        -
          Name: Deploystaging
          Actions:
            -
              Name: CreateUATChangeSet
              InputArtifacts:
                -
                  Name: CFTemplates
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              OutputArtifacts:
                -
                  Name: CreatedUATChangeSet
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                ChangeSetName: UATCBChangeSet
                RoleArn: !GetAtt CloudFormationRole.Arn
                StackName: !Sub "UAT-${AWS::StackName}"
                TemplatePath: CFTemplates::cf.yml
                TemplateConfiguration: CFTemplates::cf-parameters.json
                ParameterOverrides: !Sub |
                  {
                    "MinSize": "1",
                    "MaxSize": "1"
                  }
              RunOrder: 1
            -
              Name: ExecuteUATChangeSet
              InputArtifacts:
                -
                  Name: CreatedUATChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: UATCBChangeSet
                StackName: !Sub "UAT-${AWS::StackName}"
              RunOrder: 2
            -
              Name: CBTest
              InputArtifacts:
                - Name: github
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CBTest
              RunOrder: 3
        -
          Name: StopStaging
          Actions:
            -
              Name: StopStagingChangeSet
              InputArtifacts:
                -
                  Name: CFTemplates
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              OutputArtifacts:
                -
                  Name: StopStagingUATChangeSet
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                ChangeSetName: StopStagingChangeSet
                RoleArn: !GetAtt CloudFormationRole.Arn
                StackName: !Sub "UAT-${AWS::StackName}"
                TemplatePath: CFTemplates::cf.yml
                TemplateConfiguration: CFTemplates::cf-parameters.json
                ParameterOverrides: !Sub |
                  {
                    "MinSize": "0",
                    "MaxSize": "0"
                  }
              RunOrder: 1
            -
              Name: ExecuteStopChangeSet
              InputArtifacts:
                -
                  Name: StopStagingUATChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: StopStagingChangeSet
                StackName: !Sub "UAT-${AWS::StackName}"
              RunOrder: 2


      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
