- name: Update everything
  apt:
    upgrade: dist
    update_cache: yes

- name: Install base packages
  apt:
    state: present
    pkg: "{{item}}"
  with_items:
    - emacs
    - awesome
    - awesome-extra
    - net-tools
    - openssh-server

- name: Install Unattended-upgrades
  apt: name=unattended-upgrades

- name: Manage etc
  synchronize:
    src: etc
    dest: /
    archive: no
    recursive: yes
  notify: dconf-db

- name: ssh-server
  systemd: state=started name=ssh
