- name: Spotify apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90

- name: Spotify Repo
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present

- name: Google apt key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: Google Repo
  apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main

- name: Update everything
  apt:
    upgrade: dist
    update_cache: yes

- name: Install base packages
  apt:
    state: present
    pkg: "{{item}}"
  with_items:
    - curl
    - emacs
    - net-tools
    - openconnect
    - openssh-server
    - openconnect
    - qemu
    - rar
    - smbclient
    - unattended-upgrades
    - zsh
    - netfilter-persistent
    - iptables-persistent

- name: Install Desktop
  apt:
    state: present
    pkg: "{{item}}"
  with_items:
    - audacity
    - awesome
    - awesome-extra
    - google-chrome-stable
    - gparted
    - dconf-cli
    - fancontrol
    - lm-sensors
    - net-tools
    - network-manager-openconnect
    - network-manager-openconnect-gnome
    - pavucontrol
    - pwgen
    - pm-utils
    - transmission-gtk
    - tree
    - spotify-client
    - virt-manager
    - virt-viewer
    - vlc
    - xscreensaver

- name: Install Dev tools
  apt:
    state: present
    pkg: "{{item}}"
  with_items:
    - ansible
    - checkinstall
    - chromium-chromedriver
    - docker
    - docker.io
    - python-setuptools
    - python3-pip
    - python-pip
    - ruby
    - virtualbox
    - virtualenv

- name: Install Sec tools
  apt:
    state: present
    pkg: "{{item}}"
  with_items:
    - nmap
    - ngrep
    - tor
    - wireshark

- name: Mange etc
  synchronize:
    src: etc
    dest: /
    checksum: yes
    archive: no
    recursive: yes
  notify:
    - dconf-db
    - netfilter-persistent

- name: Update GDM CSS
  file:
    src: /etc/gdm3/gdm3.css
    dest: /etc/alternatives/gdm3.css
    owner: root
    group: root
    state: link

- name: Add user
  user:
    name: a
    shell: /bin/zsh
    groups: adm,sudo,plugdev,libvirt,libvirt-qemu,docker

- name: Manage home .files
  synchronize:
    src: home/a
    dest: /home/
    archive: no
    checksum: yes
    recursive: yes

- name: Oh my zsh
  git:
    repo: https://GitHub.com/robbyrussell/oh-my-zsh.git
    dest: /home/a/.oh-my-zsh

- name: emacs prelude
  git:
    repo: https://github.com/bbatsov/prelude.git
    dest: /home/a/.emacs.d

- name: ssh-server
  systemd:
    name: ssh
    enabled: yes
    state: started

- name: netfilter-persistent
  systemd:
    name: netfilter-persistent
    enabled: yes
    state: started

# - name: cups
#   systemd:
#     name: cups
#     enabled: no
#     state: stopped

- name: tor
  systemd:
    name: tor
    enabled: no
    state: stopped

# - name: Schedule automatic ansible updates
#   cron:
#     name: ansible
#     minute: 0
#     user: root
#     cron_file: ansible-update
#     job: /usr/bin/ansible-pull -U https://github.com/akinnane/playbooks.git -i localhost,

# - name: Set homedir permissions
#   file:
#     dest: /home/a
#     owner: a
#     group: a
#     mode: u=rwX, g=, o=
    # recurse: yes
