- name: Update everything
  apt:
    upgrade: dist
    update_cache: yes

- name: Install base packages
  apt:
    state: present
    pkg: "{{item}}"
  with_items:
    - emacs
    - awesome
    - awesome-extra

- name: Install Unattended-upgrades
  apt: name=unattended-upgrades

- name: GDM config
  copy:
    src: etc/gdm3/custom.conf
    dest: /etc/gdm3/custom.conf
    owner: root
    group: root
