- name: Spotify apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90

- name: Spotify Repo
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present

- name: Google apt key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub

- name: Google Repo
  apt_repository:
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main

- name: Update everything
  apt:
    upgrade: dist
    update_cache: yes

- name: Install base packages
  apt:
    state: present
    pkg:
    - curl
    - emacs
    - iptables-persistent
    - netfilter-persistent
    - net-tools
    - openconnect
    - openconnect
    - openssh-server
    - qemu
    - rar
    - smbclient
    - unattended-upgrades
    - zsh

- name: Install Desktop
  apt:
    state: present
    pkg:
    - awesome
    - awesome-extra
    - dconf-cli
    - google-chrome-stable
    - gparted
    - net-tools
    - network-manager-openconnect
    - network-manager-openconnect-gnome
    - pavucontrol
    - pwgen
    - transmission-gtk
    - tree
    - xscreensaver

- name: Install Desktop media
  apt:
    state: present
    pkg:
    - audacity
    - gimp
    - gstreamer1.0-libav
    - gstreamer1.0-vaapi
    - libva2
    - lastpass-cli
    - spotify-client
    - ubuntu-restricted-extras
    - va-driver-all
    - vainfo
    - vlc
    - xscreensaver

- name: Install power tools
  apt:
    state: present
    pkg:
    - fancontrol
    - i7z
    - lm-sensors
    - pm-utils
    - powerstat
    - powertop
    - tlp

- name: Install virtualisation tools
  apt:
    state: present
    pkg:
    - ovmf
    # - qemu-system-gui
    - qemu-system-x86
    - virt-manager
    - virtualbox
    - virtualenv
    - virt-viewer

- name: Install Dev tools
  apt:
    state: present
    pkg:
    - ansible
    - build-essential
    - checkinstall
    - chromium-chromedriver
    - docker
    - docker.io
    - inotify-tools
    - libbz2-dev
    - libpcap-dev
    - yasm
    - libgmp-dev
    - libpcap-dev
    - libnss3-dev
    - libkrb5-dev
    - pkg-config
    - libbz2-dev
    - zlib1g-dev
    - nvidia-cuda-toolkit
    - nvidia-opencl-dev
    - libssl-dev
    - python3-pip
    - python-pip
    - python-setuptools
    - ruby
    - strace
    - zlib1g-dev

- name: Install Sec tools
  apt:
    state: present
    pkg:
    - aircrack-ng
    - clamav
    - dsniff
    - etherape
    - ettercap-graphical
    - hashcat-nvidia
    - hping3
    - john
    - kismet
    - masscan
    - mtr
    - nbtscan
    - ngrep
    - ngrep
    - nmap
    - radare2
    - rkhunter
    - scapy
    - tcptrace
    - tor
    - wireshark
    - whois
    - zmap

- name: Security Repos
  git:
    depth: 1
    repo: "{{item}}.git"
    dest: "/home/a/github/security/tools/{{item.split('/')[-1]}}"
  with_items:
    - https://github.com/bettercap/bettercap
    - https://github.com/duo-labs/cloudmapper
    - https://github.com/gophish/gophish
    - https://github.com/jofpin/trape
    - https://github.com/michenriksen/gitrob
    - https://github.com/mitmproxy/mitmproxy
    - https://github.com/NullArray/AutoSploit
    - https://github.com/samratashok/nishang
    - https://github.com/duo-labs/cloudmapper
    - https://github.com/rapid7/metasploit-framework
    - https://github.com/secdev/scapy
    - https://github.com/wpscanteam/wpscan
    - https://github.com/zricethezav/gitleaks
    - https://github.com/hashcat/hashcat
    - https://github.com/magnumripper/JohnTheRipper

- name: Security - Docs
  git:
    depth: 1
    repo: "https://github.com/{{item}}"
    dest: "/home/a/work/github/{{item}}"
  with_items:
    - apsdehal/awesome-ctf
    - Developer-Y/cs-video-courses
    - drduh/macOS-Security-and-Privacy-Guide
    - drduh/YubiKey-Guide
    - forter/security-101-for-saas-startups
    - Hack-with-Github/Awesome-Hacking
    - hslatman/awesome-threat-intelligence
    - LOLBAS-Project/LOLBAS
    - meirwah/awesome-incident-response
    - paragonie/awesome-appsec
    - PaulSec/awesome-sec-talks
    - qazbnm456/awesome-web-security
    - sbilly/awesome-security
    - shieldfy/API-Security-Checklist
    - trimstray/test-your-sysadmin-skills
    - trimstray/the-book-of-secret-knowledge
    - vinta/awesome-python
    - xairy/linux-kernel-exploitation

- name: Sec - WiFi
  git:
    depth: 1
    repo: "https://github.com/{{item}}"
    dest: "/home/a/work/github/{{item}}"
  with_items:
    - wifiphisher/wifiphisher

# - name: Rust
#   git:
#     depth: 1
#     repo: "https://github.com/{{item}}"
#     dest: "/home/a/work/github/{{item}}"
#   with_items:
#     - rust-unofficial/patterns
#     - mre/idiomatic-rust
#     - rust-lang/rust
#     - rust-unofficial/awesome-rust

- name: Mange etc
  synchronize:
    src: etc
    dest: /
    checksum: yes
    archive: no
    recursive: yes
  notify:
    - dconf-db
    - netfilter-persistent

- name: Update GDM CSS
  file:
    src: /etc/gdm3/gdm3.css
    dest: /etc/alternatives/gdm3.css
    owner: root
    group: root
    state: link

- name: Add user
  user:
    name: a
    shell: /bin/zsh
    groups: adm,sudo,plugdev,libvirt,libvirt-qemu,docker

- name: Manage home .files
  synchronize:
    src: home/a
    dest: /home/
    archive: no
    checksum: yes
    recursive: yes

- name: Oh my zsh
  git:
    depth: 1
    repo: https://GitHub.com/robbyrussell/oh-my-zsh.git
    dest: /home/a/.oh-my-zsh

- name: emacs prelude
  git:
    update: no
    repo: https://github.com/bbatsov/prelude.git
    dest: /home/a/.emacs.d

- name: ssh-server
  systemd:
    name: ssh
    enabled: yes
    state: started

- name: netfilter-persistent
  systemd:
    name: netfilter-persistent
    enabled: yes
    state: started

- name: Stop services
  systemd:
    name: "{{item}}"
    enabled: no
    state: stopped
  with_items:
  - cups
  - avahi-daemon
  - bluetooth
  - clamav-freshclam
  - colord
  - cups-browsed
  - ModemManager
  - postfix

- name: tor
  systemd:
    name: tor
    enabled: no
    state: stopped

# - name: Schedule automatic ansible updates
#   cron:
#     name: ansible
#     minute: 0
#     user: root
#     cron_file: ansible-update
#     job: /usr/bin/ansible-pull -U https://github.com/akinnane/playbooks.git -i localhost,

- name: Set homedir permissions
  file:
    dest: /home/a
    owner: a
    group: a
    recurse: yes

- name: Set authorized key
  authorized_key:
    user: a
    state: present
    key: "{{item}}"
  with_items:
    - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOgqbXbHoy9sGxcOXW+gU9CwR9uYctNQ32O0TwD7AclB a@xps"
