- name: Install base packages
  apt:
    state: present
    pkg: "{{item}}"
  with_items:
    - i8kutils
    - nvidia-driver-390
    - xbacklight
    - xserver-xorg-input-libinput

- name: Remove xps specific packages
  apt:
    state: absent
    pkg: "{{item}}"
  with_items:
    - xserver-xorg-input-synaptics

- name: Manage etc
  synchronize:
    src: etc
    dest: /
    checksum: yes
    archive: no
    recursive: yes
  notify:
    - update-grub2

- name: Manage home
  synchronize:
    src: a
    dest: /home
    checksum: yes
    archive: no
    recursive: yes

- name: libinput
  copy:
    src: files/40-libinput.conf
    dest: /usr/share/X11/xorg.conf.d/40-libinput.conf
    owner: root
    group: root
